"""
Churn Analysis Validator
========================

Purpose:
    Validate the outputs generated by churn_analysis.py.

Input:
    outputs/feature_engineering/customer_analytical_features.xlsx

Validation targets:
    - Churn KPI reconciliation
    - Customer-level integrity
    - Output file existence
    - Segment-level mathematical integrity
    - Driver summary integrity
    - Numerical churn comparison integrity
    - Risk segment integrity
    - Retention analysis integrity
    - Consolidated report integrity

Output:
    outputs/validation_reports/churn_analysis_validation_report.xlsx
"""

from pathlib import Path

import numpy as np
import pandas as pd


######   PROJECT PATHS   ######

PYTHON_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = PYTHON_ROOT.parent


######   FEATURE ENGINEERING INPUT   ######

FEATURE_FILE = (
    PYTHON_ROOT
    / "06_Outputs"
    / "03_feature_engineering"
    / "customer_analytical_features.xlsx"
)


######   CHURN ANALYSIS OUTPUT   ######

CHURN_ANALYSIS_DIR = (
    PYTHON_ROOT
    / "06_Outputs"
    / "05_churn_analysis"
)


######   VALIDATION REPORT   ######

VALIDATION_DIR = (
    PYTHON_ROOT
    / "06_Outputs"
    / "09_validation_reports"
)

VALIDATION_REPORT = (
    VALIDATION_DIR
    / "churn_analysis_validation_report.xlsx"
)

######   EXPECTED OUTPUT FILES   ######

EXPECTED_OUTPUT_FILES = [
    "churn_kpi_summary.xlsx",
    "churn_by_customer_profile.xlsx",
    "churn_by_subscription.xlsx",
    "churn_by_payment.xlsx",
    "churn_by_services.xlsx",
    "churn_by_support.xlsx",
    "churn_by_engagement.xlsx",
    "churn_numerical_comparison.xlsx",
    "churn_risk_segments.xlsx",
    "combined_churn_risk_segments.xlsx",
    "churn_driver_summary.xlsx",
    "retention_analysis.xlsx",
    "churn_analysis_report.xlsx",
]

######   EXPECTED SHEETS   ######

EXPECTED_PROFILE_SHEETS = [
    "gender",
    "age_group",
    "state",
    "signup_year",
    "signup_quarter",
]

EXPECTED_SUBSCRIPTION_SHEETS = [
    "plan",
    "plan_category",
    "contract_type",
    "contract_category",
    "monthly_charge_band",
    "tenure_segment",
]

EXPECTED_PAYMENT_SHEETS = [
    "primary_payment_method",
    "payment_activity_segment",
    "payment_value_segment",
    "payment_failure_flag",
    "low_payment_success_flag",
]

EXPECTED_SERVICE_SHEETS = [
    "mobile_app",
    "streaming",
    "cloud_storage",
    "premium_support",
    "family_plan",
    "service_adoption_segment",
]

EXPECTED_SUPPORT_SHEETS = [
    "support_usage_segment",
    "support_experience_segment",
    "support_risk_flag",
    "support_experience_risk",
    "high_support_usage",
    "has_unresolved_ticket",
    "has_low_satisfaction",
]

EXPECTED_ENGAGEMENT_SHEETS = [
    "customer_engagement_level",
    "high_value_customer",
]

EXPECTED_NUMERICAL_SHEETS = [
    "Num_age",
    "Num_monthly_charge",
    "Num_tenure_days",
    "Num_tenure_months",
    "Num_total_payment_count",
    "Num_total_payment_amount",
    "Num_payment_success_rate",
    "Num_payment_failure_rate",
    "Num_payments_per_month",
    "Num_total_ticket_count",
    "Num_average_resolution_time_hou",
    "Num_average_satisfaction_score",
    "Num_ticket_resolution_rate",
    "Num_tickets_per_month",
    "Num_service_count",
    "Num_service_adoption_rate",
    "Num_customer_engagement_score",
]

EXPECTED_REPORT_SHEETS = (
    [
        "Churn_KPIs",
        "Risk_Segments",
        "Combined_Risk",
        "Driver_Summary",
    ]
    + EXPECTED_NUMERICAL_SHEETS
)

######   REQUIRED SEGMENT COLUMNS   ######

REQUIRED_SEGMENT_COLUMNS = [
    "customer_count",
    "churned_customers",
    "churn_rate",
    "retained_customers",
    "retention_rate",
]

######   HELPER FUNCTIONS   ######

def add_check(
    checks,
    check_name,
    category,
    actual_value,
    expected_value,
    status,
    description,
):
    """Append one validation result."""

    checks.append(
        {
            "Check_Name": check_name,
            "Category": category,
            "Actual_Value": actual_value,
            "Expected_Value": expected_value,
            "Status": status,
            "Description": description,
        }
    )


def load_excel_sheet(
    file_path,
    sheet_name=0,
):
    """Load one Excel sheet."""

    return pd.read_excel(
        file_path,
        sheet_name=sheet_name,
    )


def validate_required_columns(
    df,
    required_columns,
):
    """Return missing required columns."""

    return sorted(
        set(required_columns)
        - set(df.columns)
    )


def validate_segment_dataframe(
    df,
):
    """
    Validate common segment-level calculations.

    Returns:
        invalid_count
        messages
    """

    invalid_count = 0
    messages = []

    required = set(REQUIRED_SEGMENT_COLUMNS)

    missing = required - set(df.columns)

    if missing:
        return (
            len(missing),
            [
                f"Missing required columns: {sorted(missing)}"
            ],
        )

    
    # Customer counts
    

    invalid_customer_count = (
        pd.to_numeric(
            df["customer_count"],
            errors="coerce",
        )
        < 0
    )

    count = int(
        invalid_customer_count.sum()
    )

    if count > 0:
        invalid_count += count
        messages.append(
            f"{count} negative customer counts."
        )

    # Churned customers    

    invalid_churned_count = (
        pd.to_numeric(
            df["churned_customers"],
            errors="coerce",
        )
        < 0
    )

    count = int(
        invalid_churned_count.sum()
    )

    if count > 0:
        invalid_count += count
        messages.append(
            f"{count} negative churned-customer counts."
        )

    # Churned <= customers    

    customer_count = pd.to_numeric(
        df["customer_count"],
        errors="coerce",
    )

    churned_count = pd.to_numeric(
        df["churned_customers"],
        errors="coerce",
    )

    invalid_relationship = (
        churned_count > customer_count
    )

    count = int(
        invalid_relationship.sum()
    )

    if count > 0:
        invalid_count += count
        messages.append(
            f"{count} rows have churned customers greater "
            "than total customers."
        )
  
    # Retained = customers - churned    

    if "retained_customers" in df.columns:

        retained_count = pd.to_numeric(
            df["retained_customers"],
            errors="coerce",
        )

        expected_retained = (
            customer_count
            - churned_count
        )

        invalid_retained = ~np.isclose(
            retained_count,
            expected_retained,
            atol=0.01,
            equal_nan=False,
        )

        count = int(
            invalid_retained.sum()
        )

        if count > 0:
            invalid_count += count
            messages.append(
                f"{count} rows have incorrect retained-customer counts."
            )
 
    # Churn rate    

    churn_rate = pd.to_numeric(
        df["churn_rate"],
        errors="coerce",
    )

    invalid_churn_rate = (
        (churn_rate < 0)
        | (churn_rate > 100)
        | churn_rate.isna()
    )

    count = int(
        invalid_churn_rate.sum()
    )

    if count > 0:
        invalid_count += count
        messages.append(
            f"{count} invalid churn-rate values."
        )
    
    # Retention rate   

    retention_rate = pd.to_numeric(
        df["retention_rate"],
        errors="coerce",
    )

    invalid_retention_rate = (
        (retention_rate < 0)
        | (retention_rate > 100)
        | retention_rate.isna()
    )

    count = int(
        invalid_retention_rate.sum()
    )

    if count > 0:
        invalid_count += count
        messages.append(
            f"{count} invalid retention-rate values."
        )
    
    # Churn + Retention = 100

    invalid_rate_sum = ~np.isclose(
        churn_rate + retention_rate,
        100,
        atol=0.01,
        equal_nan=False,
    )

    count = int(
        invalid_rate_sum.sum()
    )

    if count > 0:
        invalid_count += count
        messages.append(
            f"{count} rows where churn rate + retention rate "
            "does not equal approximately 100%."
        )

    return invalid_count, messages

# MAIN VALIDATION

def main():

    print("CHURN ANALYSIS VALIDATION")
    print("\n")

    VALIDATION_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    checks = []

    # 1. LOAD SOURCE DATA    

    print("\nLoading validation datasets...")

    if not FEATURE_FILE.exists():

        add_check(
            checks,
            "Feature dataset exists",
            "Source Integrity",
            0,
            1,
            "FAIL",
            "Feature-engineered dataset was not found.",
        )

        source_df = pd.DataFrame()

    else:

        source_df = pd.read_excel(
            FEATURE_FILE
        )

        add_check(
            checks,
            "Feature dataset exists",
            "Source Integrity",
            1,
            1,
            "PASS",
            "Feature-engineered dataset exists.",
        )

    # 2. SOURCE DATASET INTEGRITY    

    if not source_df.empty:

        add_check(
            checks,
            "Source row count",
            "Source Integrity",
            len(source_df),
            20000,
            "PASS"
            if len(source_df) == 20000
            else "FAIL",
            "Churn analysis must use 20,000 customer records.",
        )

        add_check(
            checks,
            "Customer ID uniqueness",
            "Source Integrity",
            source_df["customer_id"].nunique(),
            len(source_df),
            "PASS"
            if source_df["customer_id"].nunique()
            == len(source_df)
            else "FAIL",
            "Each customer must appear exactly once.",
        )

        add_check(
            checks,
            "Churn target validity",
            "Source Integrity",
            sorted(
                source_df["churn_target"]
                .dropna()
                .unique()
                .tolist()
            ),
            [0, 1],
            "PASS"
            if set(
                source_df["churn_target"]
                .dropna()
                .unique()
            ).issubset({0, 1})
            else "FAIL",
            "Churn target must contain only 0 and 1.",
        )

        source_churned = int(
            source_df["churn_target"].sum()
        )

        source_active = (
            len(source_df)
            - source_churned
        )

        source_churn_rate = round(
            source_churned
            / len(source_df)
            * 100,
            2,
        )

    else:

        source_churned = 0
        source_active = 0
        source_churn_rate = 0

    # 3. OUTPUT FILE EXISTENCE    

    missing_files = []

    for filename in EXPECTED_OUTPUT_FILES:

        file_path = (
            CHURN_ANALYSIS_DIR
            / filename
        )

        if not file_path.exists():
            missing_files.append(filename)

    add_check(
        checks,
        "Required output files",
        "Output Integrity",
        len(EXPECTED_OUTPUT_FILES)
        - len(missing_files),
        len(EXPECTED_OUTPUT_FILES),
        "PASS"
        if not missing_files
        else "FAIL",
        (
            "All expected churn-analysis output files exist."
            if not missing_files
            else f"Missing files: {missing_files}"
        ),
    )
    
    # 4. KPI VALIDATION    

    KPI_FILE = (
        CHURN_ANALYSIS_DIR
        / "churn_kpi_summary.xlsx"
    )

    if KPI_FILE.exists():

        kpi_df = pd.read_excel(
            KPI_FILE
        )

        kpi_dict = dict(
            zip(
                kpi_df["metric"],
                kpi_df["value"],
            )
        )

        actual_total = int(
            kpi_dict.get(
                "Total Customers",
                -1,
            )
        )

        actual_churned = int(
            kpi_dict.get(
                "Churned Customers",
                -1,
            )
        )

        actual_active = int(
            kpi_dict.get(
                "Active Customers",
                -1,
            )
        )

        actual_churn_rate = float(
            kpi_dict.get(
                "Churn Rate (%)",
                np.nan,
            )
        )

        actual_retention_rate = float(
            kpi_dict.get(
                "Retention Rate (%)",
                np.nan,
            )
        )

        add_check(
            checks,
            "KPI total customers",
            "KPI Integrity",
            actual_total,
            20000,
            "PASS"
            if actual_total == 20000
            else "FAIL",
            "KPI total customers must equal source customers.",
        )

        add_check(
            checks,
            "KPI churned customers",
            "KPI Integrity",
            actual_churned,
            source_churned,
            "PASS"
            if actual_churned == source_churned
            else "FAIL",
            "KPI churned customers must reconcile to churn target.",
        )

        add_check(
            checks,
            "KPI active customers",
            "KPI Integrity",
            actual_active,
            source_active,
            "PASS"
            if actual_active == source_active
            else "FAIL",
            "KPI active customers must reconcile to source data.",
        )

        add_check(
            checks,
            "KPI churn rate",
            "KPI Integrity",
            actual_churn_rate,
            source_churn_rate,
            "PASS"
            if np.isclose(
                actual_churn_rate,
                source_churn_rate,
                atol=0.01,
            )
            else "FAIL",
            "KPI churn rate must reconcile to churn target.",
        )

        expected_retention_rate = round(
            100 - source_churn_rate,
            2,
        )

        add_check(
            checks,
            "KPI retention rate",
            "KPI Integrity",
            actual_retention_rate,
            expected_retention_rate,
            "PASS"
            if np.isclose(
                actual_retention_rate,
                expected_retention_rate,
                atol=0.01,
            )
            else "FAIL",
            "Retention rate must equal 100% minus churn rate.",
        )

    else:

        add_check(
            checks,
            "KPI workbook",
            "KPI Integrity",
            0,
            1,
            "FAIL",
            "Churn KPI workbook does not exist.",
        )
    
    # 5. PROFILE / CATEGORY WORKBOOK VALIDATION    

    category_workbooks = {
        "churn_by_customer_profile.xlsx":
            EXPECTED_PROFILE_SHEETS,

        "churn_by_subscription.xlsx":
            EXPECTED_SUBSCRIPTION_SHEETS,

        "churn_by_payment.xlsx":
            EXPECTED_PAYMENT_SHEETS,

        "churn_by_services.xlsx":
            EXPECTED_SERVICE_SHEETS,

        "churn_by_support.xlsx":
            EXPECTED_SUPPORT_SHEETS,

        "churn_by_engagement.xlsx":
            EXPECTED_ENGAGEMENT_SHEETS,
    }

    for filename, expected_sheets in category_workbooks.items():

        file_path = (
            CHURN_ANALYSIS_DIR
            / filename
        )

        if not file_path.exists():
            continue

        workbook = pd.ExcelFile(
            file_path
        )

        missing_sheets = sorted(
            set(expected_sheets)
            - set(workbook.sheet_names)
        )

        add_check(
            checks,
            f"{filename} sheet coverage",
            "Output Integrity",
            len(expected_sheets)
            - len(missing_sheets),
            len(expected_sheets),
            "PASS"
            if not missing_sheets
            else "FAIL",
            (
                "All expected analysis sheets exist."
                if not missing_sheets
                else f"Missing sheets: {missing_sheets}"
            ),
        )
    
    # 6. SEGMENT-LEVEL VALIDATION    

    profile_files = list(
        category_workbooks.keys()
    )

    segment_error_count = 0
    segment_error_messages = []

    for filename in profile_files:

        file_path = (
            CHURN_ANALYSIS_DIR
            / filename
        )

        if not file_path.exists():
            continue

        workbook = pd.ExcelFile(
            file_path
        )

        for sheet_name in workbook.sheet_names:

            df = pd.read_excel(
                file_path,
                sheet_name=sheet_name,
            )

            invalid_count, messages = (
                validate_segment_dataframe(df)
            )

            segment_error_count += invalid_count

            segment_error_messages.extend(
                [
                    f"{filename}/{sheet_name}: {message}"
                    for message in messages
                ]
            )

    add_check(
        checks,
        "Category segment integrity",
        "Analytical Integrity",
        segment_error_count,
        0,
        "PASS"
        if segment_error_count == 0
        else "FAIL",
        (
            "All category-level churn calculations are mathematically valid."
            if segment_error_count == 0
            else "; ".join(segment_error_messages)
        ),
    )
    
    # 7. DRIVER SUMMARY VALIDATION
    
    DRIVER_FILE = (
        CHURN_ANALYSIS_DIR
        / "churn_driver_summary.xlsx"
    )

    if DRIVER_FILE.exists():

        driver_df = pd.read_excel(
            DRIVER_FILE
        )

        required_driver_columns = [
            "feature",
            "segment",
            "customer_count",
            "churned_customers",
            "churn_rate",
            "overall_churn_rate",
            "churn_rate_difference",
        ]

        missing_driver_columns = (
            validate_required_columns(
                driver_df,
                required_driver_columns,
            )
        )

        add_check(
            checks,
            "Driver summary columns",
            "Driver Integrity",
            len(required_driver_columns)
            - len(missing_driver_columns),
            len(required_driver_columns),
            "PASS"
            if not missing_driver_columns
            else "FAIL",
            (
                "All driver-summary columns exist."
                if not missing_driver_columns
                else f"Missing columns: {missing_driver_columns}"
            ),
        )

        if not missing_driver_columns:

            invalid_driver_counts = (
                (
                    driver_df["customer_count"]
                    < 0
                )
                |
                (
                    driver_df["churned_customers"]
                    < 0
                )
                |
                (
                    driver_df["churned_customers"]
                    > driver_df["customer_count"]
                )
            )

            add_check(
                checks,
                "Driver customer counts",
                "Driver Integrity",
                int(
                    invalid_driver_counts.sum()
                ),
                0,
                "PASS"
                if not invalid_driver_counts.any()
                else "FAIL",
                "Driver customer counts must be valid.",
            )

            invalid_driver_rates = (
                (
                    driver_df["churn_rate"]
                    < 0
                )
                |
                (
                    driver_df["churn_rate"]
                    > 100
                )
            )

            add_check(
                checks,
                "Driver churn rates",
                "Driver Integrity",
                int(
                    invalid_driver_rates.sum()
                ),
                0,
                "PASS"
                if not invalid_driver_rates.any()
                else "FAIL",
                "Driver churn rates must be between 0% and 100%.",
            )

            invalid_overall_rate = (
                ~np.isclose(
                    driver_df[
                        "overall_churn_rate"
                    ],
                    source_churn_rate,
                    atol=0.01,
                )
            )

            add_check(
                checks,
                "Driver overall churn rate",
                "Driver Integrity",
                int(
                    invalid_overall_rate.sum()
                ),
                0,
                "PASS"
                if not invalid_overall_rate.any()
                else "FAIL",
                "Driver summary must use the validated overall churn rate.",
            )

            expected_difference = (
                driver_df["churn_rate"]
                - driver_df["overall_churn_rate"]
            )

            invalid_difference = (
                ~np.isclose(
                    driver_df[
                        "churn_rate_difference"
                    ],
                    expected_difference,
                    atol=0.01,
                )
            )

            add_check(
                checks,
                "Driver churn-rate difference",
                "Driver Integrity",
                int(
                    invalid_difference.sum()
                ),
                0,
                "PASS"
                if not invalid_difference.any()
                else "FAIL",
                "Churn-rate difference must equal segment rate minus overall rate.",
            )
    
    # 8. RISK SEGMENT VALIDATION
    
    RISK_FILE = (
        CHURN_ANALYSIS_DIR
        / "churn_risk_segments.xlsx"
    )

    if RISK_FILE.exists():

        risk_df = pd.read_excel(
            RISK_FILE
        )

        required_risk_columns = [
            "segment_variable",
            "customer_count",
            "churned_customers",
            "churn_rate",
            "retained_customers",
            "retention_rate",
        ]

        missing_risk_columns = (
            validate_required_columns(
                risk_df,
                required_risk_columns,
            )
        )

        add_check(
            checks,
            "Risk segment columns",
            "Risk Integrity",
            len(required_risk_columns)
            - len(missing_risk_columns),
            len(required_risk_columns),
            "PASS"
            if not missing_risk_columns
            else "FAIL",
            (
                "All risk-segment columns exist."
                if not missing_risk_columns
                else f"Missing columns: {missing_risk_columns}"
            ),
        )

        if not missing_risk_columns:

            invalid_count, messages = (
                validate_segment_dataframe(
                    risk_df
                )
            )

            add_check(
                checks,
                "Risk segment mathematical integrity",
                "Risk Integrity",
                invalid_count,
                0,
                "PASS"
                if invalid_count == 0
                else "FAIL",
                (
                    "Risk-segment calculations are valid."
                    if invalid_count == 0
                    else "; ".join(messages)
                ),
            )
    
    # 9. COMBINED RISK VALIDATION
    
    COMBINED_RISK_FILE = (
        CHURN_ANALYSIS_DIR
        / "combined_churn_risk_segments.xlsx"
    )

    if COMBINED_RISK_FILE.exists():

        combined_df = pd.read_excel(
            COMBINED_RISK_FILE
        )

        required_combined_columns = [
            "segment_combination",
            "customer_count",
            "churned_customers",
            "churn_rate",
            "retention_rate",
        ]

        missing_combined_columns = (
            validate_required_columns(
                combined_df,
                required_combined_columns,
            )
        )

        add_check(
            checks,
            "Combined risk columns",
            "Risk Integrity",
            len(required_combined_columns)
            - len(missing_combined_columns),
            len(required_combined_columns),
            "PASS"
            if not missing_combined_columns
            else "FAIL",
            (
                "All combined-risk columns exist."
                if not missing_combined_columns
                else f"Missing columns: {missing_combined_columns}"
            ),
        )

        if not missing_combined_columns:

            customer_count = pd.to_numeric(
                combined_df["customer_count"],
                errors="coerce",
            )

            churned_count = pd.to_numeric(
                combined_df["churned_customers"],
                errors="coerce",
            )

            churn_rate = pd.to_numeric(
                combined_df["churn_rate"],
                errors="coerce",
            )

            retention_rate = pd.to_numeric(
                combined_df["retention_rate"],
                errors="coerce",
            )

            invalid_combined = (
                (customer_count < 0)
                | (churned_count < 0)
                | (churned_count > customer_count)
                | (churn_rate < 0)
                | (churn_rate > 100)
                | (retention_rate < 0)
                | (retention_rate > 100)
                | ~np.isclose(
                    churn_rate + retention_rate,
                    100,
                    atol=0.01,
                )
            )

            add_check(
                checks,
                "Combined risk mathematical integrity",
                "Risk Integrity",
                int(
                    invalid_combined.sum()
                ),
                0,
                "PASS"
                if not invalid_combined.any()
                else "FAIL",
                "Combined risk calculations must be mathematically valid.",
            )
    
    # 10. NUMERICAL CHURN COMPARISON
    
    NUMERICAL_FILE = (
        CHURN_ANALYSIS_DIR
        / "churn_numerical_comparison.xlsx"
    )

    if NUMERICAL_FILE.exists():

        numerical_workbook = pd.ExcelFile(
            NUMERICAL_FILE
        )

        missing_numerical_sheets = sorted(
            set(
                [
                    "age",
                    "monthly_charge",
                    "tenure_days",
                    "tenure_months",
                    "total_payment_count",
                    "total_payment_amount",
                    "payment_success_rate",
                    "payment_failure_rate",
                    "payments_per_month",
                    "total_ticket_count",
                    "average_resolution_time_hours",
                    "average_satisfaction_score",
                    "ticket_resolution_rate",
                    "tickets_per_month",
                    "service_count",
                    "service_adoption_rate",
                    "customer_engagement_score",
                ]
            )
            - set(
                numerical_workbook.sheet_names
            )
        )

        add_check(
            checks,
            "Numerical churn comparison sheets",
            "Numerical Integrity",
            len(
                numerical_workbook.sheet_names
            ),
            17,
            "PASS"
            if not missing_numerical_sheets
            else "FAIL",
            (
                "All expected numerical comparison sheets exist."
                if not missing_numerical_sheets
                else f"Missing sheets: {missing_numerical_sheets}"
            ),
        )

        numerical_errors = []

        for sheet_name in numerical_workbook.sheet_names:

            df = pd.read_excel(
                NUMERICAL_FILE,
                sheet_name=sheet_name,
            )

            required_columns = [
                "churn_target",
                "churn_status",
                "customer_count",
                "mean",
                "median",
                "std",
                "min",
                "max",
            ]

            missing = (
                validate_required_columns(
                    df,
                    required_columns,
                )
            )

            if missing:
                numerical_errors.append(
                    f"{sheet_name}: missing {missing}"
                )
                continue

            churn_targets = set(
                df["churn_target"]
                .dropna()
                .astype(int)
                .tolist()
            )

            if not {0, 1}.issubset(
                churn_targets
            ):
                numerical_errors.append(
                    f"{sheet_name}: missing Active/Churned groups"
                )

        add_check(
            checks,
            "Numerical churn comparison integrity",
            "Numerical Integrity",
            len(numerical_errors),
            0,
            "PASS"
            if not numerical_errors
            else "FAIL",
            (
                "Numerical churn comparisons are valid."
                if not numerical_errors
                else "; ".join(numerical_errors)
            ),
        )
    
    # 11. RETENTION ANALYSIS
    
    RETENTION_FILE = (
        CHURN_ANALYSIS_DIR
        / "retention_analysis.xlsx"
    )

    if RETENTION_FILE.exists():

        retention_workbook = pd.ExcelFile(
            RETENTION_FILE
        )

        expected_retention_sheets = [
            "age_group",
            "plan_category",
            "contract_category",
            "tenure_segment",
            "payment_activity_segment",
            "service_adoption_segment",
            "support_experience_segment",
            "customer_engagement_level",
        ]

        missing_retention_sheets = sorted(
            set(expected_retention_sheets)
            - set(retention_workbook.sheet_names)
        )

        add_check(
            checks,
            "Retention analysis sheets",
            "Retention Integrity",
            len(expected_retention_sheets)
            - len(missing_retention_sheets),
            len(expected_retention_sheets),
            "PASS"
            if not missing_retention_sheets
            else "FAIL",
            (
                "All expected retention-analysis sheets exist."
                if not missing_retention_sheets
                else f"Missing sheets: {missing_retention_sheets}"
            ),
        )

        retention_errors = []

        for sheet_name in retention_workbook.sheet_names:

            df = pd.read_excel(
                RETENTION_FILE,
                sheet_name=sheet_name,
            )

            required_columns = [
                "customer_count",
                "churned_customers",
                "retained_customers",
                "churn_rate",
                "retention_rate",
            ]

            missing = (
                validate_required_columns(
                    df,
                    required_columns,
                )
            )

            if missing:
                retention_errors.append(
                    f"{sheet_name}: missing {missing}"
                )
                continue

            invalid_rates = (
                (
                    df["churn_rate"] < 0
                )
                |
                (
                    df["churn_rate"] > 100
                )
                |
                (
                    df["retention_rate"] < 0
                )
                |
                (
                    df["retention_rate"] > 100
                )
                |
                ~np.isclose(
                    df["churn_rate"]
                    + df["retention_rate"],
                    100,
                    atol=0.01,
                )
            )

            if invalid_rates.any():
                retention_errors.append(
                    f"{sheet_name}: invalid churn/retention rates"
                )

        add_check(
            checks,
            "Retention analysis integrity",
            "Retention Integrity",
            len(retention_errors),
            0,
            "PASS"
            if not retention_errors
            else "FAIL",
            (
                "Retention analysis calculations are valid."
                if not retention_errors
                else "; ".join(retention_errors)
            ),
        )
    
    # 12. CONSOLIDATED REPORT
    
    REPORT_FILE = (
        CHURN_ANALYSIS_DIR
        / "churn_analysis_report.xlsx"
    )

    if REPORT_FILE.exists():

        report_workbook = pd.ExcelFile(
            REPORT_FILE
        )

        missing_report_sheets = sorted(
            set(EXPECTED_REPORT_SHEETS)
            - set(report_workbook.sheet_names)
        )

        add_check(
            checks,
            "Consolidated report sheets",
            "Report Integrity",
            len(EXPECTED_REPORT_SHEETS)
            - len(missing_report_sheets),
            len(EXPECTED_REPORT_SHEETS),
            "PASS"
            if not missing_report_sheets
            else "FAIL",
            (
                "All expected consolidated-report sheets exist."
                if not missing_report_sheets
                else f"Missing sheets: {missing_report_sheets}"
            ),
        )
    
    # 13. GLOBAL CHURN RECONCILIATION
    
    add_check(
        checks,
        "Global churn reconciliation",
        "Analytical Integrity",
        source_churned + source_active,
        20000,
        "PASS"
        if source_churned + source_active == 20000
        else "FAIL",
        "Churned plus active customers must equal total customers.",
    )
    
    # 14. FINAL VALIDATION SUMMARY    

    validation_df = pd.DataFrame(
        checks
    )

    total_checks = len(
        validation_df
    )

    passed_checks = int(
        (
            validation_df["Status"]
            == "PASS"
        ).sum()
    )

    failed_checks = int(
        (
            validation_df["Status"]
            == "FAIL"
        ).sum()
    )

    info_checks = int(
        (
            validation_df["Status"]
            == "INFO"
        ).sum()
    )

    overall_status = (
        "PASS"
        if failed_checks == 0
        else "FAIL"
    )
    
    # WRITE REPORT
    
    validation_df.to_excel(
        VALIDATION_REPORT,
        sheet_name="Validation_Results",
        index=False,
    )

    summary_df = pd.DataFrame(
        [
            {
                "Metric": "Total Checks",
                "Value": total_checks,
            },
            {
                "Metric": "Passed Checks",
                "Value": passed_checks,
            },
            {
                "Metric": "Failed Checks",
                "Value": failed_checks,
            },
            {
                "Metric": "Info Checks",
                "Value": info_checks,
            },
            {
                "Metric": "Overall Validation",
                "Value": overall_status,
            },
            {
                "Metric": "Source Customers",
                "Value": len(source_df),
            },
            {
                "Metric": "Churned Customers",
                "Value": source_churned,
            },
            {
                "Metric": "Active Customers",
                "Value": source_active,
            },
            {
                "Metric": "Churn Rate (%)",
                "Value": source_churn_rate,
            },
        ]
    )

    with pd.ExcelWriter(
        VALIDATION_REPORT,
        engine="openpyxl",
    ) as writer:

        validation_df.to_excel(
            writer,
            sheet_name="Validation_Results",
            index=False,
        )

        summary_df.to_excel(
            writer,
            sheet_name="Summary",
            index=False,
        )

    # CONSOLE OUTPUT    

    print("CHURN ANALYSIS VALIDATION RESULTS")
    print("\n")

    print(
        f"Total Checks  : {total_checks}"
    )

    print(
        f"Passed Checks : {passed_checks}"
    )

    print(
        f"Failed Checks : {failed_checks}"
    )

    print(
        f"Info Checks   : {info_checks}"
    )

    print(
        f"\nOverall Churn Analysis Validation : "
        f"{overall_status}"
    )

    print(
        "\nValidation Report:"
    )

    print(
        VALIDATION_REPORT
    )

    print("CHURN ANALYSIS VALIDATION COMPLETED")
    print("\n")
    print(
        f"Source customers      : {len(source_df):,}"
    )

    print(
        f"Churned customers     : {source_churned:,}"
    )

    print(
        f"Active customers      : {source_active:,}"
    )

    print(
        f"Churn rate            : {source_churn_rate:.2f}%"
    )

    print(
        f"Overall validation    : {overall_status}"
    )


if __name__ == "__main__":
    main()