"""
Customer Churn & Retention Analysis
EDA Independent Validator

Purpose
-------
Independently validate the outputs generated by eda.py.

Analytical grain
----------------
1 row = 1 customer

Source Dataset
--------------
outputs/feature_engineering/customer_analytical_features.xlsx

EDA Outputs
-----------
outputs/eda/

Validation Output
-----------------
outputs/validation_reports/eda_validation_report.xlsx

"""

from pathlib import Path
import numpy as np
import pandas as pd


######   PROJECT PATHS   ######

PYTHON_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = PYTHON_ROOT.parent


######   FEATURE ENGINEERING SOURCE   ######

SOURCE_FILE = (
    PYTHON_ROOT
    / "06_Outputs"
    / "03_feature_engineering"
    / "customer_analytical_features.xlsx"
)


######   EDA OUTPUT DIRECTORY   ######

EDA_DIR = (
    PYTHON_ROOT
    / "06_Outputs"
    / "02_eda"
)


######   EDA OUTPUT FILES   ######

SUMMARY_FILE = (
    EDA_DIR
    / "eda_summary_report.xlsx"
)

COLUMN_PROFILE_FILE = (
    EDA_DIR
    / "column_profile.xlsx"
)

CATEGORICAL_FILE = (
    EDA_DIR
    / "categorical_analysis.xlsx"
)

NUMERICAL_FILE = (
    EDA_DIR
    / "numerical_analysis.xlsx"
)

CHURN_FILE = (
    EDA_DIR
    / "churn_analysis.xlsx"
)

SEGMENT_FILE = (
    EDA_DIR
    / "segment_analysis.xlsx"
)

CORRELATION_FILE = (
    EDA_DIR
    / "correlation_analysis.xlsx"
)

EDA_REPORT_FILE = (
    EDA_DIR
    / "eda_report.xlsx"
)


######   VALIDATION REPORT   ######

REPORT_FILE = (
    PYTHON_ROOT
    / "06_Outputs"
    / "09_validation_reports"
    / "eda_validation_report.xlsx"
)


######   EXPECTED ENGINEERED FEATURES   ######

EXPECTED_ENGINEERED_FEATURES = [
    "age_group",
    "signup_year",
    "signup_month",
    "signup_quarter",
    "annual_subscription_value",
    "monthly_charge_band",
    "plan_category",
    "contract_category",
    "churn_target",
    "payment_failure_flag",
    "payment_activity_segment",
    "payment_value_segment",
    "service_count",
    "service_adoption_rate",
    "service_adoption_segment",
    "support_usage_segment",
    "support_experience_segment",
    "support_risk_flag",
    "customer_engagement_score",
    "customer_engagement_level",
    "high_value_customer",
    "low_payment_success_flag",
    "support_experience_risk",
]


######   HELPER FUNCTIONS   ######

def standardize_columns(df):
    """
    Standardize dataframe column names.
    """

    df = df.copy()

    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
    )

    return df

def add_check(
    checks,
    check_name,
    category,
    actual_value,
    expected_value,
    status,
    description,
):
    """
    Add a validation check to the validation results.
    """

    checks.append(
        {
            "Check_Name": check_name,
            "Category": category,
            "Actual_Value": actual_value,
            "Expected_Value": expected_value,
            "Status": status,
            "Description": description,
        }
    )

def load_excel(path):
    """
    Load an Excel file after confirming that it exists.
    """

    if not path.exists():

        raise FileNotFoundError(
            f"Required EDA file not found:\n{path}"
        )

    return pd.read_excel(path)


######   MAIN VALIDATION   ######

def main():

    print("EDA VALIDATION")
    print("\n")

    # LOAD DATA    

    print("\nLoading validation datasets...")

    if not SOURCE_FILE.exists():

        raise FileNotFoundError(
            f"Source feature dataset not found:\n{SOURCE_FILE}"
        )

    source_df = pd.read_excel(
        SOURCE_FILE
    )

    source_df = standardize_columns(
        source_df
    )
    
    # LOAD EDA OUTPUTS
    
    summary_df = load_excel(
        SUMMARY_FILE
    )

    profile_df = load_excel(
        COLUMN_PROFILE_FILE
    )

    categorical_df = load_excel(
        CATEGORICAL_FILE
    )

    numerical_df = load_excel(
        NUMERICAL_FILE
    )

    # Load workbooks only to confirm their sheets exist.
    churn_xlsx = pd.ExcelFile(
        CHURN_FILE
    )

    segment_xlsx = pd.ExcelFile(
        SEGMENT_FILE
    )

    correlation_xlsx = pd.ExcelFile(
        CORRELATION_FILE
    )

    report_df = load_excel(
        EDA_REPORT_FILE
    )

    checks = []
    
    # 1. SOURCE DATASET VALIDATION
    
    source_rows = len(
        source_df
    )

    source_columns = len(
        source_df.columns
    )
    
    # Source row count
    
    add_check(
        checks,
        "Source row count",
        "Dataset Integrity",
        source_rows,
        20000,
        "PASS"
        if source_rows == 20000
        else "FAIL",
        "EDA must analyze all 20,000 customer records.",
    )
    
    # Source column count
    
    add_check(
        checks,
        "Source column count",
        "Dataset Integrity",
        source_columns,
        119,
        "PASS"
        if source_columns == 119
        else "FAIL",
        "EDA must analyze the validated 119-column feature dataset.",
    )

    # Unique customers
    
    if "customer_id" in source_df.columns:

        unique_customers = (
            source_df["customer_id"]
            .nunique()
        )

    else:

        unique_customers = 0

    add_check(
        checks,
        "Unique customer count",
        "Dataset Integrity",
        unique_customers,
        20000,
        "PASS"
        if unique_customers == 20000
        else "FAIL",
        "Analytical grain must remain one row per customer.",
    )
    
    # Duplicate customer IDs
    
    if "customer_id" in source_df.columns:

        duplicate_customers = int(
            source_df["customer_id"]
            .duplicated()
            .sum()
        )

    else:

        duplicate_customers = -1

    add_check(
        checks,
        "Duplicate customer IDs",
        "Dataset Integrity",
        duplicate_customers,
        0,
        "PASS"
        if duplicate_customers == 0
        else "FAIL",
        "EDA source must contain no duplicate customer IDs.",
    )
    
    # 2. FEATURE AVAILABILITY
    
    missing_features = [
        column
        for column in EXPECTED_ENGINEERED_FEATURES
        if column not in source_df.columns
    ]

    add_check(
        checks,
        "Required feature columns",
        "Feature Availability",
        len(missing_features),
        0,
        "PASS"
        if len(missing_features) == 0
        else "FAIL",
        (
            "All expected engineered features are available."
            if len(missing_features) == 0
            else f"Missing features: {missing_features}"
        ),
    )
    
    # 3. CHURN TARGET VALIDATION
    
    if "churn_target" in source_df.columns:

        invalid_target = int(
            (
                ~source_df["churn_target"]
                .isin([0, 1])
            ).sum()
        )

        churned = int(
            (
                source_df["churn_target"] == 1
            ).sum()
        )

        active = int(
            (
                source_df["churn_target"] == 0
            ).sum()
        )

    else:

        invalid_target = -1
        churned = -1
        active = -1
    
    # Churn target values
    
    add_check(
        checks,
        "Churn target values",
        "Churn Integrity",
        invalid_target,
        0,
        "PASS"
        if invalid_target == 0
        else "FAIL",
        "Churn target must contain only 0 and 1.",
    )
    
    # Churned customer count
    
    add_check(
        checks,
        "Churned customer count",
        "Churn Integrity",
        churned,
        4463,
        "PASS"
        if churned == 4463
        else "FAIL",
        "Churned customers must reconcile to the validated churn layer.",
    )
    
    # Active customer count
    
    add_check(
        checks,
        "Active customer count",
        "Churn Integrity",
        active,
        15537,
        "PASS"
        if active == 15537
        else "FAIL",
        "Active customers must reconcile to the validated churn layer.",
    )
    
    # 4. EDA SUMMARY OUTPUT
    
    summary_rows = len(
        summary_df
    )

    add_check(
        checks,
        "EDA summary report exists",
        "Output Integrity",
        summary_rows,
        ">0",
        "PASS"
        if summary_rows > 0
        else "FAIL",
        "EDA summary workbook must contain a summary table.",
    )
    
    # 5. COLUMN PROFILE VALIDATION
    
    profile_rows = len(
        profile_df
    )

    add_check(
        checks,
        "Column profile coverage",
        "Output Integrity",
        profile_rows,
        119,
        "PASS"
        if profile_rows == 119
        else "FAIL",
        "Column profile must contain one record for every feature column.",
    )
    
    # 6. NUMERICAL ANALYSIS COVERAGE
    
    # Numeric columns expected in the EDA numerical-analysis output.
    #
    # has_churn_date and has_end_date are technical/data-quality
    # indicators. They are intentionally excluded from numerical
    # analysis coverage because they are used to indicate the
    # presence/absence of outcome dates rather than being analytical
    # measures.

    NUMERICAL_ANALYSIS_EXCLUSIONS = {
        "has_churn_date",
        "has_end_date",
    }

    expected_numeric_columns = (
        set(source_df.select_dtypes(include=np.number).columns)
        - NUMERICAL_ANALYSIS_EXCLUSIONS
    )

    actual_numeric_columns = set()

    if not numerical_df.empty:

        if "Column" in numerical_df.columns:
            actual_numeric_columns = set(
                numerical_df["Column"]
                .dropna()
                .astype(str)
                .str.strip()
            )

        elif "column" in numerical_df.columns:
            actual_numeric_columns = set(
                numerical_df["column"]
                .dropna()
                .astype(str)
                .str.strip()
            )

        elif "column_name" in numerical_df.columns:
            actual_numeric_columns = set(
                numerical_df["column_name"]
                .dropna()
                .astype(str)
                .str.strip()
            )

    missing_numeric_columns = sorted(
        expected_numeric_columns - actual_numeric_columns
    )

    unexpected_numeric_columns = sorted(
        actual_numeric_columns - expected_numeric_columns
    )

    if not missing_numeric_columns and not unexpected_numeric_columns:

        numerical_coverage_status = "PASS"

        numerical_coverage_message = (
            "Numerical analysis covers all numeric feature columns."
        )

    else:

        numerical_coverage_status = "FAIL"

        numerical_coverage_message = (
            f"Missing numeric columns: {missing_numeric_columns}; "
            f"Unexpected numeric columns: {unexpected_numeric_columns}"
        )

    add_check(
        checks,
        "Numerical analysis coverage",
        "Output Integrity",
        len(missing_numeric_columns),
        0,
        numerical_coverage_status,
        numerical_coverage_message,
    )
    
    # 7. CATEGORICAL ANALYSIS
    
    add_check(
        checks,
        "Categorical analysis generated",
        "Output Integrity",
        len(categorical_df),
        ">0",
        "PASS"
        if len(categorical_df) > 0
        else "FAIL",
        "Categorical frequency analysis exists.",
    )
    
    # 8. CHURN ANALYSIS WORKBOOK
    
    churn_sheet_count = len(
        churn_xlsx.sheet_names
    )

    add_check(
        checks,
        "Churn analysis workbook",
        "Output Integrity",
        churn_sheet_count,
        ">0",
        "PASS"
        if churn_sheet_count > 0
        else "FAIL",
        "Churn analysis workbook must contain analytical sheets.",
    )
    
    # 9. SEGMENT ANALYSIS WORKBOOK
    
    segment_sheet_count = len(
        segment_xlsx.sheet_names
    )

    add_check(
        checks,
        "Segment analysis workbook",
        "Output Integrity",
        segment_sheet_count,
        ">0",
        "PASS"
        if segment_sheet_count > 0
        else "FAIL",
        "Segment analysis workbook must contain analytical sheets.",
    )
    
    # 10. CORRELATION ANALYSIS
    
    correlation_sheets = set(
        correlation_xlsx.sheet_names
    )

    required_correlation_sheets = {
        "Correlation_Matrix",
        "Correlation_Pairs",
        "Churn_Relationships",
    }

    missing_correlation_sheets = sorted(
        required_correlation_sheets
        - correlation_sheets
    )

    add_check(
        checks,
        "Correlation analysis sheets",
        "Output Integrity",
        len(missing_correlation_sheets),
        0,
        "PASS"
        if len(missing_correlation_sheets) == 0
        else "FAIL",
        (
            "All required correlation analysis sheets exist."
            if len(missing_correlation_sheets) == 0
            else (
                "Missing correlation sheets: "
                f"{missing_correlation_sheets}"
            )
        ),
    )
    
    # 11. CHURN RATE RECONCILIATION
    
    if (
        churned >= 0
        and source_rows > 0
    ):

        expected_churn_rate = (
            churned
            / source_rows
            * 100
        )

    else:

        expected_churn_rate = np.nan
    
    # Read churn rate from summary output
    
    if (
        len(summary_df) > 0
        and "Churn_Rate_Percent" in summary_df.columns
    ):

        reported_churn_rate = float(
            summary_df
            .iloc[0]["Churn_Rate_Percent"]
        )

        rate_match = np.isclose(
            reported_churn_rate,
            expected_churn_rate,
            atol=0.01,
            rtol=0,
        )

    else:

        reported_churn_rate = np.nan
        rate_match = False

    add_check(
        checks,
        "Churn rate reconciliation",
        "Churn Integrity",
        reported_churn_rate,
        round(
            expected_churn_rate,
            2,
        )
        if pd.notna(expected_churn_rate)
        else np.nan,
        "PASS"
        if rate_match
        else "FAIL",
        (
            "EDA summary churn rate reconciles with churn target."
            if rate_match
            else (
                "EDA summary churn rate does not reconcile "
                "with churn target."
            )
        ),
    )
    
    # 12. INFINITE NUMERIC VALUES
    
    numeric_df = source_df.select_dtypes(
        include=np.number
    )

    numeric_array = numeric_df.to_numpy(
        dtype="float64"
    )

    infinite_values = int(
        np.isinf(
            numeric_array
        ).sum()
    )

    add_check(
        checks,
        "Infinite numeric values in source",
        "Data Quality",
        infinite_values,
        0,
        "PASS"
        if infinite_values == 0
        else "FAIL",
        "EDA source must not contain infinite numeric values.",
    )
    
    # 13. MISSING VALUES
    
    missing_values = int(
        source_df
        .isna()
        .sum()
        .sum()
    )

    add_check(
        checks,
        "Source missing values",
        "Data Quality",
        missing_values,
        "Informational",
        "INFO",
        (
            "Missing values are profiled by EDA "
            "and are not automatically treated as errors."
        ),
    )
    
    # 14. REQUIRED OUTPUT FILES
    
    expected_files = [
        SUMMARY_FILE,
        COLUMN_PROFILE_FILE,
        CATEGORICAL_FILE,
        NUMERICAL_FILE,
        CHURN_FILE,
        SEGMENT_FILE,
        CORRELATION_FILE,
        EDA_REPORT_FILE,
    ]

    missing_files = [
        str(path)
        for path in expected_files
        if not path.exists()
    ]

    add_check(
        checks,
        "Required EDA output files",
        "Output Integrity",
        len(missing_files),
        0,
        "PASS"
        if len(missing_files) == 0
        else "FAIL",
        (
            "All required EDA output files exist."
            if len(missing_files) == 0
            else (
                "Missing EDA output files: "
                f"{missing_files}"
            )
        ),
    )
    
    # 15. EDA REPORT CONTENT
    
    add_check(
        checks,
        "EDA report generated",
        "Output Integrity",
        len(report_df),
        ">0",
        "PASS"
        if len(report_df) > 0
        else "FAIL",
        "EDA report must contain analytical completion records.",
    )
    
    # FINAL VALIDATION SUMMARY
    
    checks_df = pd.DataFrame(
        checks
    )

    passed = int(
        (
            checks_df["Status"] == "PASS"
        ).sum()
    )

    failed = int(
        (
            checks_df["Status"] == "FAIL"
        ).sum()
    )

    info = int(
        (
            checks_df["Status"] == "INFO"
        ).sum()
    )

    overall_status = (
        "PASS"
        if failed == 0
        else "FAIL"
    )
    
    # CONSOLE OUTPUT
    
    print("EDA VALIDATION RESULTS")
    print("\n")

    print(
        f"Total Checks  : {len(checks_df)}"
    )

    print(
        f"Passed Checks : {passed}"
    )

    print(
        f"Failed Checks : {failed}"
    )

    print(
        f"Info Checks   : {info}"
    )

    print(
        f"\nOverall EDA Validation : "
        f"{overall_status}"
    )
    
    # SAVE VALIDATION REPORT
    
    REPORT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    validation_summary = pd.DataFrame(
        [
            {
                "Source_Rows": source_rows,
                "Source_Columns": source_columns,
                "Unique_Customers": unique_customers,
                "Churned_Customers": churned,
                "Active_Customers": active,
                "Expected_Churn_Rate_Percent": round(
                    expected_churn_rate,
                    2,
                )
                if pd.notna(expected_churn_rate)
                else np.nan,
                "Reported_Churn_Rate_Percent": reported_churn_rate,
                "Total_Checks": len(checks_df),
                "Passed_Checks": passed,
                "Failed_Checks": failed,
                "Info_Checks": info,
                "Overall_Status": overall_status,
            }
        ]
    )

    with pd.ExcelWriter(
        REPORT_FILE,
        engine="openpyxl",
    ) as writer:

        checks_df.to_excel(
            writer,
            sheet_name="Validation_Checks",
            index=False,
        )

        validation_summary.to_excel(
            writer,
            sheet_name="Validation_Summary",
            index=False,
        )
    
    # COMPLETION MESSAGE
    
    print(
        f"\nValidation Report:\n"
        f"{REPORT_FILE}"
    )

    print("EDA VALIDATION COMPLETED")
    print("\n")

    print(
        f"Source rows             : "
        f"{source_rows:,}"
    )

    print(
        f"Source columns          : "
        f"{source_columns:,}"
    )

    print(
        f"Churned customers       : "
        f"{churned:,}"
    )

    print(
        f"Active customers        : "
        f"{active:,}"
    )

    print(
        f"Overall validation      : "
        f"{overall_status}"
    )


######   SCRIPT ENTRY POINT   ######

if __name__ == "__main__":

    main()